// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: trung.proto
// Protobuf Java Version: 4.30.0

package fish;

public final class TrungOuterClass {
  private TrungOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 0,
      /* suffix= */ "",
      TrungOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TrungOrBuilder extends
      // @@protoc_insertion_point(interface_extends:fish.Trung)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 field1 = 1;</code>
     * @return The field1.
     */
    int getField1();

    /**
     * <code>int32 field2 = 2;</code>
     * @return The field2.
     */
    int getField2();

    /**
     * <code>int32 field3 = 3;</code>
     * @return The field3.
     */
    int getField3();

    /**
     * <code>float field4 = 4;</code>
     * @return The field4.
     */
    float getField4();
  }
  /**
   * Protobuf type {@code fish.Trung}
   */
  public static final class Trung extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:fish.Trung)
      TrungOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 0,
        /* suffix= */ "",
        Trung.class.getName());
    }
    // Use Trung.newBuilder() to construct.
    private Trung(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Trung() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fish.TrungOuterClass.internal_static_fish_Trung_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fish.TrungOuterClass.internal_static_fish_Trung_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fish.TrungOuterClass.Trung.class, fish.TrungOuterClass.Trung.Builder.class);
    }

    public static final int FIELD1_FIELD_NUMBER = 1;
    private int field1_ = 0;
    /**
     * <code>int32 field1 = 1;</code>
     * @return The field1.
     */
    @java.lang.Override
    public int getField1() {
      return field1_;
    }

    public static final int FIELD2_FIELD_NUMBER = 2;
    private int field2_ = 0;
    /**
     * <code>int32 field2 = 2;</code>
     * @return The field2.
     */
    @java.lang.Override
    public int getField2() {
      return field2_;
    }

    public static final int FIELD3_FIELD_NUMBER = 3;
    private int field3_ = 0;
    /**
     * <code>int32 field3 = 3;</code>
     * @return The field3.
     */
    @java.lang.Override
    public int getField3() {
      return field3_;
    }

    public static final int FIELD4_FIELD_NUMBER = 4;
    private float field4_ = 0F;
    /**
     * <code>float field4 = 4;</code>
     * @return The field4.
     */
    @java.lang.Override
    public float getField4() {
      return field4_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (field1_ != 0) {
        output.writeInt32(1, field1_);
      }
      if (field2_ != 0) {
        output.writeInt32(2, field2_);
      }
      if (field3_ != 0) {
        output.writeInt32(3, field3_);
      }
      if (java.lang.Float.floatToRawIntBits(field4_) != 0) {
        output.writeFloat(4, field4_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (field1_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, field1_);
      }
      if (field2_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, field2_);
      }
      if (field3_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, field3_);
      }
      if (java.lang.Float.floatToRawIntBits(field4_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, field4_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof fish.TrungOuterClass.Trung)) {
        return super.equals(obj);
      }
      fish.TrungOuterClass.Trung other = (fish.TrungOuterClass.Trung) obj;

      if (getField1()
          != other.getField1()) return false;
      if (getField2()
          != other.getField2()) return false;
      if (getField3()
          != other.getField3()) return false;
      if (java.lang.Float.floatToIntBits(getField4())
          != java.lang.Float.floatToIntBits(
              other.getField4())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FIELD1_FIELD_NUMBER;
      hash = (53 * hash) + getField1();
      hash = (37 * hash) + FIELD2_FIELD_NUMBER;
      hash = (53 * hash) + getField2();
      hash = (37 * hash) + FIELD3_FIELD_NUMBER;
      hash = (53 * hash) + getField3();
      hash = (37 * hash) + FIELD4_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getField4());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static fish.TrungOuterClass.Trung parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fish.TrungOuterClass.Trung parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fish.TrungOuterClass.Trung parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fish.TrungOuterClass.Trung parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fish.TrungOuterClass.Trung parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fish.TrungOuterClass.Trung parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fish.TrungOuterClass.Trung parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static fish.TrungOuterClass.Trung parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static fish.TrungOuterClass.Trung parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static fish.TrungOuterClass.Trung parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static fish.TrungOuterClass.Trung parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static fish.TrungOuterClass.Trung parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(fish.TrungOuterClass.Trung prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code fish.Trung}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:fish.Trung)
        fish.TrungOuterClass.TrungOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fish.TrungOuterClass.internal_static_fish_Trung_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fish.TrungOuterClass.internal_static_fish_Trung_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fish.TrungOuterClass.Trung.class, fish.TrungOuterClass.Trung.Builder.class);
      }

      // Construct using fish.TrungOuterClass.Trung.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        field1_ = 0;
        field2_ = 0;
        field3_ = 0;
        field4_ = 0F;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fish.TrungOuterClass.internal_static_fish_Trung_descriptor;
      }

      @java.lang.Override
      public fish.TrungOuterClass.Trung getDefaultInstanceForType() {
        return fish.TrungOuterClass.Trung.getDefaultInstance();
      }

      @java.lang.Override
      public fish.TrungOuterClass.Trung build() {
        fish.TrungOuterClass.Trung result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public fish.TrungOuterClass.Trung buildPartial() {
        fish.TrungOuterClass.Trung result = new fish.TrungOuterClass.Trung(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(fish.TrungOuterClass.Trung result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.field1_ = field1_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.field2_ = field2_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.field3_ = field3_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.field4_ = field4_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fish.TrungOuterClass.Trung) {
          return mergeFrom((fish.TrungOuterClass.Trung)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fish.TrungOuterClass.Trung other) {
        if (other == fish.TrungOuterClass.Trung.getDefaultInstance()) return this;
        if (other.getField1() != 0) {
          setField1(other.getField1());
        }
        if (other.getField2() != 0) {
          setField2(other.getField2());
        }
        if (other.getField3() != 0) {
          setField3(other.getField3());
        }
        if (java.lang.Float.floatToRawIntBits(other.getField4()) != 0) {
          setField4(other.getField4());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                field1_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                field2_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                field3_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 37: {
                field4_ = input.readFloat();
                bitField0_ |= 0x00000008;
                break;
              } // case 37
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int field1_ ;
      /**
       * <code>int32 field1 = 1;</code>
       * @return The field1.
       */
      @java.lang.Override
      public int getField1() {
        return field1_;
      }
      /**
       * <code>int32 field1 = 1;</code>
       * @param value The field1 to set.
       * @return This builder for chaining.
       */
      public Builder setField1(int value) {

        field1_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 field1 = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearField1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        field1_ = 0;
        onChanged();
        return this;
      }

      private int field2_ ;
      /**
       * <code>int32 field2 = 2;</code>
       * @return The field2.
       */
      @java.lang.Override
      public int getField2() {
        return field2_;
      }
      /**
       * <code>int32 field2 = 2;</code>
       * @param value The field2 to set.
       * @return This builder for chaining.
       */
      public Builder setField2(int value) {

        field2_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 field2 = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearField2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        field2_ = 0;
        onChanged();
        return this;
      }

      private int field3_ ;
      /**
       * <code>int32 field3 = 3;</code>
       * @return The field3.
       */
      @java.lang.Override
      public int getField3() {
        return field3_;
      }
      /**
       * <code>int32 field3 = 3;</code>
       * @param value The field3 to set.
       * @return This builder for chaining.
       */
      public Builder setField3(int value) {

        field3_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 field3 = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearField3() {
        bitField0_ = (bitField0_ & ~0x00000004);
        field3_ = 0;
        onChanged();
        return this;
      }

      private float field4_ ;
      /**
       * <code>float field4 = 4;</code>
       * @return The field4.
       */
      @java.lang.Override
      public float getField4() {
        return field4_;
      }
      /**
       * <code>float field4 = 4;</code>
       * @param value The field4 to set.
       * @return This builder for chaining.
       */
      public Builder setField4(float value) {

        field4_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>float field4 = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearField4() {
        bitField0_ = (bitField0_ & ~0x00000008);
        field4_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:fish.Trung)
    }

    // @@protoc_insertion_point(class_scope:fish.Trung)
    private static final fish.TrungOuterClass.Trung DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new fish.TrungOuterClass.Trung();
    }

    public static fish.TrungOuterClass.Trung getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Trung>
        PARSER = new com.google.protobuf.AbstractParser<Trung>() {
      @java.lang.Override
      public Trung parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Trung> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Trung> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public fish.TrungOuterClass.Trung getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Trung2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:fish.Trung2)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .fish.Trung unknowns = 2;</code>
     */
    java.util.List<fish.TrungOuterClass.Trung> 
        getUnknownsList();
    /**
     * <code>repeated .fish.Trung unknowns = 2;</code>
     */
    fish.TrungOuterClass.Trung getUnknowns(int index);
    /**
     * <code>repeated .fish.Trung unknowns = 2;</code>
     */
    int getUnknownsCount();
    /**
     * <code>repeated .fish.Trung unknowns = 2;</code>
     */
    java.util.List<? extends fish.TrungOuterClass.TrungOrBuilder> 
        getUnknownsOrBuilderList();
    /**
     * <code>repeated .fish.Trung unknowns = 2;</code>
     */
    fish.TrungOuterClass.TrungOrBuilder getUnknownsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code fish.Trung2}
   */
  public static final class Trung2 extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:fish.Trung2)
      Trung2OrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 0,
        /* suffix= */ "",
        Trung2.class.getName());
    }
    // Use Trung2.newBuilder() to construct.
    private Trung2(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Trung2() {
      unknowns_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fish.TrungOuterClass.internal_static_fish_Trung2_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fish.TrungOuterClass.internal_static_fish_Trung2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fish.TrungOuterClass.Trung2.class, fish.TrungOuterClass.Trung2.Builder.class);
    }

    public static final int UNKNOWNS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<fish.TrungOuterClass.Trung> unknowns_;
    /**
     * <code>repeated .fish.Trung unknowns = 2;</code>
     */
    @java.lang.Override
    public java.util.List<fish.TrungOuterClass.Trung> getUnknownsList() {
      return unknowns_;
    }
    /**
     * <code>repeated .fish.Trung unknowns = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends fish.TrungOuterClass.TrungOrBuilder> 
        getUnknownsOrBuilderList() {
      return unknowns_;
    }
    /**
     * <code>repeated .fish.Trung unknowns = 2;</code>
     */
    @java.lang.Override
    public int getUnknownsCount() {
      return unknowns_.size();
    }
    /**
     * <code>repeated .fish.Trung unknowns = 2;</code>
     */
    @java.lang.Override
    public fish.TrungOuterClass.Trung getUnknowns(int index) {
      return unknowns_.get(index);
    }
    /**
     * <code>repeated .fish.Trung unknowns = 2;</code>
     */
    @java.lang.Override
    public fish.TrungOuterClass.TrungOrBuilder getUnknownsOrBuilder(
        int index) {
      return unknowns_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < unknowns_.size(); i++) {
        output.writeMessage(2, unknowns_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < unknowns_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, unknowns_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof fish.TrungOuterClass.Trung2)) {
        return super.equals(obj);
      }
      fish.TrungOuterClass.Trung2 other = (fish.TrungOuterClass.Trung2) obj;

      if (!getUnknownsList()
          .equals(other.getUnknownsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getUnknownsCount() > 0) {
        hash = (37 * hash) + UNKNOWNS_FIELD_NUMBER;
        hash = (53 * hash) + getUnknownsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static fish.TrungOuterClass.Trung2 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fish.TrungOuterClass.Trung2 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fish.TrungOuterClass.Trung2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fish.TrungOuterClass.Trung2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fish.TrungOuterClass.Trung2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fish.TrungOuterClass.Trung2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fish.TrungOuterClass.Trung2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static fish.TrungOuterClass.Trung2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static fish.TrungOuterClass.Trung2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static fish.TrungOuterClass.Trung2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static fish.TrungOuterClass.Trung2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static fish.TrungOuterClass.Trung2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(fish.TrungOuterClass.Trung2 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code fish.Trung2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:fish.Trung2)
        fish.TrungOuterClass.Trung2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fish.TrungOuterClass.internal_static_fish_Trung2_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fish.TrungOuterClass.internal_static_fish_Trung2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fish.TrungOuterClass.Trung2.class, fish.TrungOuterClass.Trung2.Builder.class);
      }

      // Construct using fish.TrungOuterClass.Trung2.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (unknownsBuilder_ == null) {
          unknowns_ = java.util.Collections.emptyList();
        } else {
          unknowns_ = null;
          unknownsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fish.TrungOuterClass.internal_static_fish_Trung2_descriptor;
      }

      @java.lang.Override
      public fish.TrungOuterClass.Trung2 getDefaultInstanceForType() {
        return fish.TrungOuterClass.Trung2.getDefaultInstance();
      }

      @java.lang.Override
      public fish.TrungOuterClass.Trung2 build() {
        fish.TrungOuterClass.Trung2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public fish.TrungOuterClass.Trung2 buildPartial() {
        fish.TrungOuterClass.Trung2 result = new fish.TrungOuterClass.Trung2(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(fish.TrungOuterClass.Trung2 result) {
        if (unknownsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            unknowns_ = java.util.Collections.unmodifiableList(unknowns_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.unknowns_ = unknowns_;
        } else {
          result.unknowns_ = unknownsBuilder_.build();
        }
      }

      private void buildPartial0(fish.TrungOuterClass.Trung2 result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fish.TrungOuterClass.Trung2) {
          return mergeFrom((fish.TrungOuterClass.Trung2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fish.TrungOuterClass.Trung2 other) {
        if (other == fish.TrungOuterClass.Trung2.getDefaultInstance()) return this;
        if (unknownsBuilder_ == null) {
          if (!other.unknowns_.isEmpty()) {
            if (unknowns_.isEmpty()) {
              unknowns_ = other.unknowns_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureUnknownsIsMutable();
              unknowns_.addAll(other.unknowns_);
            }
            onChanged();
          }
        } else {
          if (!other.unknowns_.isEmpty()) {
            if (unknownsBuilder_.isEmpty()) {
              unknownsBuilder_.dispose();
              unknownsBuilder_ = null;
              unknowns_ = other.unknowns_;
              bitField0_ = (bitField0_ & ~0x00000001);
              unknownsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetUnknownsFieldBuilder() : null;
            } else {
              unknownsBuilder_.addAllMessages(other.unknowns_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 18: {
                fish.TrungOuterClass.Trung m =
                    input.readMessage(
                        fish.TrungOuterClass.Trung.parser(),
                        extensionRegistry);
                if (unknownsBuilder_ == null) {
                  ensureUnknownsIsMutable();
                  unknowns_.add(m);
                } else {
                  unknownsBuilder_.addMessage(m);
                }
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<fish.TrungOuterClass.Trung> unknowns_ =
        java.util.Collections.emptyList();
      private void ensureUnknownsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          unknowns_ = new java.util.ArrayList<fish.TrungOuterClass.Trung>(unknowns_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          fish.TrungOuterClass.Trung, fish.TrungOuterClass.Trung.Builder, fish.TrungOuterClass.TrungOrBuilder> unknownsBuilder_;

      /**
       * <code>repeated .fish.Trung unknowns = 2;</code>
       */
      public java.util.List<fish.TrungOuterClass.Trung> getUnknownsList() {
        if (unknownsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(unknowns_);
        } else {
          return unknownsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .fish.Trung unknowns = 2;</code>
       */
      public int getUnknownsCount() {
        if (unknownsBuilder_ == null) {
          return unknowns_.size();
        } else {
          return unknownsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .fish.Trung unknowns = 2;</code>
       */
      public fish.TrungOuterClass.Trung getUnknowns(int index) {
        if (unknownsBuilder_ == null) {
          return unknowns_.get(index);
        } else {
          return unknownsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .fish.Trung unknowns = 2;</code>
       */
      public Builder setUnknowns(
          int index, fish.TrungOuterClass.Trung value) {
        if (unknownsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUnknownsIsMutable();
          unknowns_.set(index, value);
          onChanged();
        } else {
          unknownsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .fish.Trung unknowns = 2;</code>
       */
      public Builder setUnknowns(
          int index, fish.TrungOuterClass.Trung.Builder builderForValue) {
        if (unknownsBuilder_ == null) {
          ensureUnknownsIsMutable();
          unknowns_.set(index, builderForValue.build());
          onChanged();
        } else {
          unknownsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .fish.Trung unknowns = 2;</code>
       */
      public Builder addUnknowns(fish.TrungOuterClass.Trung value) {
        if (unknownsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUnknownsIsMutable();
          unknowns_.add(value);
          onChanged();
        } else {
          unknownsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .fish.Trung unknowns = 2;</code>
       */
      public Builder addUnknowns(
          int index, fish.TrungOuterClass.Trung value) {
        if (unknownsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUnknownsIsMutable();
          unknowns_.add(index, value);
          onChanged();
        } else {
          unknownsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .fish.Trung unknowns = 2;</code>
       */
      public Builder addUnknowns(
          fish.TrungOuterClass.Trung.Builder builderForValue) {
        if (unknownsBuilder_ == null) {
          ensureUnknownsIsMutable();
          unknowns_.add(builderForValue.build());
          onChanged();
        } else {
          unknownsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .fish.Trung unknowns = 2;</code>
       */
      public Builder addUnknowns(
          int index, fish.TrungOuterClass.Trung.Builder builderForValue) {
        if (unknownsBuilder_ == null) {
          ensureUnknownsIsMutable();
          unknowns_.add(index, builderForValue.build());
          onChanged();
        } else {
          unknownsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .fish.Trung unknowns = 2;</code>
       */
      public Builder addAllUnknowns(
          java.lang.Iterable<? extends fish.TrungOuterClass.Trung> values) {
        if (unknownsBuilder_ == null) {
          ensureUnknownsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, unknowns_);
          onChanged();
        } else {
          unknownsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .fish.Trung unknowns = 2;</code>
       */
      public Builder clearUnknowns() {
        if (unknownsBuilder_ == null) {
          unknowns_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          unknownsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .fish.Trung unknowns = 2;</code>
       */
      public Builder removeUnknowns(int index) {
        if (unknownsBuilder_ == null) {
          ensureUnknownsIsMutable();
          unknowns_.remove(index);
          onChanged();
        } else {
          unknownsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .fish.Trung unknowns = 2;</code>
       */
      public fish.TrungOuterClass.Trung.Builder getUnknownsBuilder(
          int index) {
        return internalGetUnknownsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .fish.Trung unknowns = 2;</code>
       */
      public fish.TrungOuterClass.TrungOrBuilder getUnknownsOrBuilder(
          int index) {
        if (unknownsBuilder_ == null) {
          return unknowns_.get(index);  } else {
          return unknownsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .fish.Trung unknowns = 2;</code>
       */
      public java.util.List<? extends fish.TrungOuterClass.TrungOrBuilder> 
           getUnknownsOrBuilderList() {
        if (unknownsBuilder_ != null) {
          return unknownsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(unknowns_);
        }
      }
      /**
       * <code>repeated .fish.Trung unknowns = 2;</code>
       */
      public fish.TrungOuterClass.Trung.Builder addUnknownsBuilder() {
        return internalGetUnknownsFieldBuilder().addBuilder(
            fish.TrungOuterClass.Trung.getDefaultInstance());
      }
      /**
       * <code>repeated .fish.Trung unknowns = 2;</code>
       */
      public fish.TrungOuterClass.Trung.Builder addUnknownsBuilder(
          int index) {
        return internalGetUnknownsFieldBuilder().addBuilder(
            index, fish.TrungOuterClass.Trung.getDefaultInstance());
      }
      /**
       * <code>repeated .fish.Trung unknowns = 2;</code>
       */
      public java.util.List<fish.TrungOuterClass.Trung.Builder> 
           getUnknownsBuilderList() {
        return internalGetUnknownsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          fish.TrungOuterClass.Trung, fish.TrungOuterClass.Trung.Builder, fish.TrungOuterClass.TrungOrBuilder> 
          internalGetUnknownsFieldBuilder() {
        if (unknownsBuilder_ == null) {
          unknownsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              fish.TrungOuterClass.Trung, fish.TrungOuterClass.Trung.Builder, fish.TrungOuterClass.TrungOrBuilder>(
                  unknowns_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          unknowns_ = null;
        }
        return unknownsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:fish.Trung2)
    }

    // @@protoc_insertion_point(class_scope:fish.Trung2)
    private static final fish.TrungOuterClass.Trung2 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new fish.TrungOuterClass.Trung2();
    }

    public static fish.TrungOuterClass.Trung2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Trung2>
        PARSER = new com.google.protobuf.AbstractParser<Trung2>() {
      @java.lang.Override
      public Trung2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Trung2> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Trung2> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public fish.TrungOuterClass.Trung2 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fish_Trung_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_fish_Trung_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fish_Trung2_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_fish_Trung2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013trung.proto\022\004fish\"G\n\005Trung\022\016\n\006field1\030\001" +
      " \001(\005\022\016\n\006field2\030\002 \001(\005\022\016\n\006field3\030\003 \001(\005\022\016\n\006" +
      "field4\030\004 \001(\002\"\'\n\006Trung2\022\035\n\010unknowns\030\002 \003(\013" +
      "2\013.fish.Trungb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_fish_Trung_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_fish_Trung_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_fish_Trung_descriptor,
        new java.lang.String[] { "Field1", "Field2", "Field3", "Field4", });
    internal_static_fish_Trung2_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_fish_Trung2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_fish_Trung2_descriptor,
        new java.lang.String[] { "Unknowns", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
