// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hit.proto
// Protobuf Java Version: 4.30.0

package protocol;

public final class Hit {
  private Hit() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 0,
      /* suffix= */ "",
      Hit.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HitReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.HitReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 bulletId = 1;</code>
     * @return The bulletId.
     */
    int getBulletId();

    /**
     * <pre>
     * ✅ fishId là mảng
     * </pre>
     *
     * <code>repeated uint32 fishId = 2;</code>
     * @return A list containing the fishId.
     */
    java.util.List<java.lang.Integer> getFishIdList();
    /**
     * <pre>
     * ✅ fishId là mảng
     * </pre>
     *
     * <code>repeated uint32 fishId = 2;</code>
     * @return The count of fishId.
     */
    int getFishIdCount();
    /**
     * <pre>
     * ✅ fishId là mảng
     * </pre>
     *
     * <code>repeated uint32 fishId = 2;</code>
     * @param index The index of the element to return.
     * @return The fishId at the given index.
     */
    int getFishId(int index);

    /**
     * <code>uint32 hits = 3;</code>
     * @return The hits.
     */
    int getHits();
  }
  /**
   * Protobuf type {@code protocol.HitReq}
   */
  public static final class HitReq extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protocol.HitReq)
      HitReqOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 0,
        /* suffix= */ "",
        HitReq.class.getName());
    }
    // Use HitReq.newBuilder() to construct.
    private HitReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private HitReq() {
      fishId_ = emptyIntList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Hit.internal_static_protocol_HitReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Hit.internal_static_protocol_HitReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Hit.HitReq.class, protocol.Hit.HitReq.Builder.class);
    }

    public static final int BULLETID_FIELD_NUMBER = 1;
    private int bulletId_ = 0;
    /**
     * <code>uint32 bulletId = 1;</code>
     * @return The bulletId.
     */
    @java.lang.Override
    public int getBulletId() {
      return bulletId_;
    }

    public static final int FISHID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList fishId_ =
        emptyIntList();
    /**
     * <pre>
     * ✅ fishId là mảng
     * </pre>
     *
     * <code>repeated uint32 fishId = 2;</code>
     * @return A list containing the fishId.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getFishIdList() {
      return fishId_;
    }
    /**
     * <pre>
     * ✅ fishId là mảng
     * </pre>
     *
     * <code>repeated uint32 fishId = 2;</code>
     * @return The count of fishId.
     */
    public int getFishIdCount() {
      return fishId_.size();
    }
    /**
     * <pre>
     * ✅ fishId là mảng
     * </pre>
     *
     * <code>repeated uint32 fishId = 2;</code>
     * @param index The index of the element to return.
     * @return The fishId at the given index.
     */
    public int getFishId(int index) {
      return fishId_.getInt(index);
    }
    private int fishIdMemoizedSerializedSize = -1;

    public static final int HITS_FIELD_NUMBER = 3;
    private int hits_ = 0;
    /**
     * <code>uint32 hits = 3;</code>
     * @return The hits.
     */
    @java.lang.Override
    public int getHits() {
      return hits_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (bulletId_ != 0) {
        output.writeUInt32(1, bulletId_);
      }
      if (getFishIdList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(fishIdMemoizedSerializedSize);
      }
      for (int i = 0; i < fishId_.size(); i++) {
        output.writeUInt32NoTag(fishId_.getInt(i));
      }
      if (hits_ != 0) {
        output.writeUInt32(3, hits_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (bulletId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, bulletId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < fishId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(fishId_.getInt(i));
        }
        size += dataSize;
        if (!getFishIdList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        fishIdMemoizedSerializedSize = dataSize;
      }
      if (hits_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, hits_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.Hit.HitReq)) {
        return super.equals(obj);
      }
      protocol.Hit.HitReq other = (protocol.Hit.HitReq) obj;

      if (getBulletId()
          != other.getBulletId()) return false;
      if (!getFishIdList()
          .equals(other.getFishIdList())) return false;
      if (getHits()
          != other.getHits()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BULLETID_FIELD_NUMBER;
      hash = (53 * hash) + getBulletId();
      if (getFishIdCount() > 0) {
        hash = (37 * hash) + FISHID_FIELD_NUMBER;
        hash = (53 * hash) + getFishIdList().hashCode();
      }
      hash = (37 * hash) + HITS_FIELD_NUMBER;
      hash = (53 * hash) + getHits();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.Hit.HitReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Hit.HitReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Hit.HitReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Hit.HitReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Hit.HitReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Hit.HitReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Hit.HitReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Hit.HitReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static protocol.Hit.HitReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static protocol.Hit.HitReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.Hit.HitReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Hit.HitReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.Hit.HitReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.HitReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.HitReq)
        protocol.Hit.HitReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Hit.internal_static_protocol_HitReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Hit.internal_static_protocol_HitReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Hit.HitReq.class, protocol.Hit.HitReq.Builder.class);
      }

      // Construct using protocol.Hit.HitReq.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        bulletId_ = 0;
        fishId_ = emptyIntList();
        hits_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Hit.internal_static_protocol_HitReq_descriptor;
      }

      @java.lang.Override
      public protocol.Hit.HitReq getDefaultInstanceForType() {
        return protocol.Hit.HitReq.getDefaultInstance();
      }

      @java.lang.Override
      public protocol.Hit.HitReq build() {
        protocol.Hit.HitReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protocol.Hit.HitReq buildPartial() {
        protocol.Hit.HitReq result = new protocol.Hit.HitReq(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(protocol.Hit.HitReq result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.bulletId_ = bulletId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          fishId_.makeImmutable();
          result.fishId_ = fishId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.hits_ = hits_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Hit.HitReq) {
          return mergeFrom((protocol.Hit.HitReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Hit.HitReq other) {
        if (other == protocol.Hit.HitReq.getDefaultInstance()) return this;
        if (other.getBulletId() != 0) {
          setBulletId(other.getBulletId());
        }
        if (!other.fishId_.isEmpty()) {
          if (fishId_.isEmpty()) {
            fishId_ = other.fishId_;
            fishId_.makeImmutable();
            bitField0_ |= 0x00000002;
          } else {
            ensureFishIdIsMutable();
            fishId_.addAll(other.fishId_);
          }
          onChanged();
        }
        if (other.getHits() != 0) {
          setHits(other.getHits());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                bulletId_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                int v = input.readUInt32();
                ensureFishIdIsMutable();
                fishId_.addInt(v);
                break;
              } // case 16
              case 18: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureFishIdIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  fishId_.addInt(input.readUInt32());
                }
                input.popLimit(limit);
                break;
              } // case 18
              case 24: {
                hits_ = input.readUInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int bulletId_ ;
      /**
       * <code>uint32 bulletId = 1;</code>
       * @return The bulletId.
       */
      @java.lang.Override
      public int getBulletId() {
        return bulletId_;
      }
      /**
       * <code>uint32 bulletId = 1;</code>
       * @param value The bulletId to set.
       * @return This builder for chaining.
       */
      public Builder setBulletId(int value) {

        bulletId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 bulletId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBulletId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bulletId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList fishId_ = emptyIntList();
      private void ensureFishIdIsMutable() {
        if (!fishId_.isModifiable()) {
          fishId_ = makeMutableCopy(fishId_);
        }
        bitField0_ |= 0x00000002;
      }
      /**
       * <pre>
       * ✅ fishId là mảng
       * </pre>
       *
       * <code>repeated uint32 fishId = 2;</code>
       * @return A list containing the fishId.
       */
      public java.util.List<java.lang.Integer>
          getFishIdList() {
        fishId_.makeImmutable();
        return fishId_;
      }
      /**
       * <pre>
       * ✅ fishId là mảng
       * </pre>
       *
       * <code>repeated uint32 fishId = 2;</code>
       * @return The count of fishId.
       */
      public int getFishIdCount() {
        return fishId_.size();
      }
      /**
       * <pre>
       * ✅ fishId là mảng
       * </pre>
       *
       * <code>repeated uint32 fishId = 2;</code>
       * @param index The index of the element to return.
       * @return The fishId at the given index.
       */
      public int getFishId(int index) {
        return fishId_.getInt(index);
      }
      /**
       * <pre>
       * ✅ fishId là mảng
       * </pre>
       *
       * <code>repeated uint32 fishId = 2;</code>
       * @param index The index to set the value at.
       * @param value The fishId to set.
       * @return This builder for chaining.
       */
      public Builder setFishId(
          int index, int value) {

        ensureFishIdIsMutable();
        fishId_.setInt(index, value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ✅ fishId là mảng
       * </pre>
       *
       * <code>repeated uint32 fishId = 2;</code>
       * @param value The fishId to add.
       * @return This builder for chaining.
       */
      public Builder addFishId(int value) {

        ensureFishIdIsMutable();
        fishId_.addInt(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ✅ fishId là mảng
       * </pre>
       *
       * <code>repeated uint32 fishId = 2;</code>
       * @param values The fishId to add.
       * @return This builder for chaining.
       */
      public Builder addAllFishId(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureFishIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fishId_);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ✅ fishId là mảng
       * </pre>
       *
       * <code>repeated uint32 fishId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFishId() {
        fishId_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private int hits_ ;
      /**
       * <code>uint32 hits = 3;</code>
       * @return The hits.
       */
      @java.lang.Override
      public int getHits() {
        return hits_;
      }
      /**
       * <code>uint32 hits = 3;</code>
       * @param value The hits to set.
       * @return This builder for chaining.
       */
      public Builder setHits(int value) {

        hits_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 hits = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHits() {
        bitField0_ = (bitField0_ & ~0x00000004);
        hits_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protocol.HitReq)
    }

    // @@protoc_insertion_point(class_scope:protocol.HitReq)
    private static final protocol.Hit.HitReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.Hit.HitReq();
    }

    public static protocol.Hit.HitReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HitReq>
        PARSER = new com.google.protobuf.AbstractParser<HitReq>() {
      @java.lang.Override
      public HitReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<HitReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HitReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protocol.Hit.HitReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_HitReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_HitReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\thit.proto\022\010protocol\"8\n\006HitReq\022\020\n\010bulle" +
      "tId\030\001 \001(\r\022\016\n\006fishId\030\002 \003(\r\022\014\n\004hits\030\003 \001(\rb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protocol_HitReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_HitReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_HitReq_descriptor,
        new java.lang.String[] { "BulletId", "FishId", "Hits", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
