// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Point2.proto
// Protobuf Java Version: 4.30.0

package protocol;

public final class Point2 {
  private Point2() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 0,
      /* suffix= */ "",
      Point2.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code protocol.BulletType2}
   */
  public enum BulletType2
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Normal = 0;</code>
     */
    Normal(0),
    /**
     * <code>Lock = 1;</code>
     */
    Lock(1),
    /**
     * <code>Dragon = 2;</code>
     */
    Dragon(2),
    /**
     * <code>DragonOther = 3;</code>
     */
    DragonOther(3),
    /**
     * <code>Phoenix = 4;</code>
     */
    Phoenix(4),
    /**
     * <code>Drill = 5;</code>
     */
    Drill(5),
    /**
     * <code>Laser = 6;</code>
     */
    Laser(6),
    /**
     * <code>Fire = 7;</code>
     */
    Fire(7),
    /**
     * <code>Free = 20;</code>
     */
    Free(20),
    /**
     * <code>FreeDrill = 21;</code>
     */
    FreeDrill(21),
    /**
     * <code>FreeNet = 22;</code>
     */
    FreeNet(22),
    /**
     * <code>Energy = 23;</code>
     */
    Energy(23),
    /**
     * <code>FreeSpin = 24;</code>
     */
    FreeSpin(24),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 0,
        /* suffix= */ "",
        BulletType2.class.getName());
    }
    /**
     * <code>Normal = 0;</code>
     */
    public static final int Normal_VALUE = 0;
    /**
     * <code>Lock = 1;</code>
     */
    public static final int Lock_VALUE = 1;
    /**
     * <code>Dragon = 2;</code>
     */
    public static final int Dragon_VALUE = 2;
    /**
     * <code>DragonOther = 3;</code>
     */
    public static final int DragonOther_VALUE = 3;
    /**
     * <code>Phoenix = 4;</code>
     */
    public static final int Phoenix_VALUE = 4;
    /**
     * <code>Drill = 5;</code>
     */
    public static final int Drill_VALUE = 5;
    /**
     * <code>Laser = 6;</code>
     */
    public static final int Laser_VALUE = 6;
    /**
     * <code>Fire = 7;</code>
     */
    public static final int Fire_VALUE = 7;
    /**
     * <code>Free = 20;</code>
     */
    public static final int Free_VALUE = 20;
    /**
     * <code>FreeDrill = 21;</code>
     */
    public static final int FreeDrill_VALUE = 21;
    /**
     * <code>FreeNet = 22;</code>
     */
    public static final int FreeNet_VALUE = 22;
    /**
     * <code>Energy = 23;</code>
     */
    public static final int Energy_VALUE = 23;
    /**
     * <code>FreeSpin = 24;</code>
     */
    public static final int FreeSpin_VALUE = 24;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BulletType2 valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static BulletType2 forNumber(int value) {
      switch (value) {
        case 0: return Normal;
        case 1: return Lock;
        case 2: return Dragon;
        case 3: return DragonOther;
        case 4: return Phoenix;
        case 5: return Drill;
        case 6: return Laser;
        case 7: return Fire;
        case 20: return Free;
        case 21: return FreeDrill;
        case 22: return FreeNet;
        case 23: return Energy;
        case 24: return FreeSpin;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BulletType2>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        BulletType2> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BulletType2>() {
            public BulletType2 findValueByNumber(int number) {
              return BulletType2.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protocol.Point2.getDescriptor().getEnumTypes().get(0);
    }

    private static final BulletType2[] VALUES = values();

    public static BulletType2 valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private BulletType2(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protocol.BulletType2)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Point2.proto\022\010protocol*\255\001\n\013BulletType2" +
      "\022\n\n\006Normal\020\000\022\010\n\004Lock\020\001\022\n\n\006Dragon\020\002\022\017\n\013Dr" +
      "agonOther\020\003\022\013\n\007Phoenix\020\004\022\t\n\005Drill\020\005\022\t\n\005L" +
      "aser\020\006\022\010\n\004Fire\020\007\022\010\n\004Free\020\024\022\r\n\tFreeDrill\020" +
      "\025\022\013\n\007FreeNet\020\026\022\n\n\006Energy\020\027\022\014\n\010FreeSpin\020\030" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
