// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ShootAck.proto
// Protobuf Java Version: 4.30.0

package protocol;

public final class ShootAckOuterClass {
  private ShootAckOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 0,
      /* suffix= */ "",
      ShootAckOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ShootAckOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.ShootAck)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.protocol.ShootReq data = 1;</code>
     * @return Whether the data field is set.
     */
    boolean hasData();
    /**
     * <code>.protocol.ShootReq data = 1;</code>
     * @return The data.
     */
    protocol.LC.ShootReq getData();
    /**
     * <code>.protocol.ShootReq data = 1;</code>
     */
    protocol.LC.ShootReqOrBuilder getDataOrBuilder();

    /**
     * <code>uint32 seat = 2;</code>
     * @return The seat.
     */
    int getSeat();

    /**
     * <code>float coin = 3;</code>
     * @return The coin.
     */
    float getCoin();

    /**
     * <code>float remain = 4;</code>
     * @return The remain.
     */
    float getRemain();
  }
  /**
   * Protobuf type {@code protocol.ShootAck}
   */
  public static final class ShootAck extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protocol.ShootAck)
      ShootAckOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 0,
        /* suffix= */ "",
        ShootAck.class.getName());
    }
    // Use ShootAck.newBuilder() to construct.
    private ShootAck(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ShootAck() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.ShootAckOuterClass.internal_static_protocol_ShootAck_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.ShootAckOuterClass.internal_static_protocol_ShootAck_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.ShootAckOuterClass.ShootAck.class, protocol.ShootAckOuterClass.ShootAck.Builder.class);
    }

    private int bitField0_;
    public static final int DATA_FIELD_NUMBER = 1;
    private protocol.LC.ShootReq data_;
    /**
     * <code>.protocol.ShootReq data = 1;</code>
     * @return Whether the data field is set.
     */
    @java.lang.Override
    public boolean hasData() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.protocol.ShootReq data = 1;</code>
     * @return The data.
     */
    @java.lang.Override
    public protocol.LC.ShootReq getData() {
      return data_ == null ? protocol.LC.ShootReq.getDefaultInstance() : data_;
    }
    /**
     * <code>.protocol.ShootReq data = 1;</code>
     */
    @java.lang.Override
    public protocol.LC.ShootReqOrBuilder getDataOrBuilder() {
      return data_ == null ? protocol.LC.ShootReq.getDefaultInstance() : data_;
    }

    public static final int SEAT_FIELD_NUMBER = 2;
    private int seat_ = 0;
    /**
     * <code>uint32 seat = 2;</code>
     * @return The seat.
     */
    @java.lang.Override
    public int getSeat() {
      return seat_;
    }

    public static final int COIN_FIELD_NUMBER = 3;
    private float coin_ = 0F;
    /**
     * <code>float coin = 3;</code>
     * @return The coin.
     */
    @java.lang.Override
    public float getCoin() {
      return coin_;
    }

    public static final int REMAIN_FIELD_NUMBER = 4;
    private float remain_ = 0F;
    /**
     * <code>float remain = 4;</code>
     * @return The remain.
     */
    @java.lang.Override
    public float getRemain() {
      return remain_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getData());
      }
      if (seat_ != 0) {
        output.writeUInt32(2, seat_);
      }
      if (java.lang.Float.floatToRawIntBits(coin_) != 0) {
        output.writeFloat(3, coin_);
      }
      if (java.lang.Float.floatToRawIntBits(remain_) != 0) {
        output.writeFloat(4, remain_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getData());
      }
      if (seat_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, seat_);
      }
      if (java.lang.Float.floatToRawIntBits(coin_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, coin_);
      }
      if (java.lang.Float.floatToRawIntBits(remain_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, remain_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.ShootAckOuterClass.ShootAck)) {
        return super.equals(obj);
      }
      protocol.ShootAckOuterClass.ShootAck other = (protocol.ShootAckOuterClass.ShootAck) obj;

      if (hasData() != other.hasData()) return false;
      if (hasData()) {
        if (!getData()
            .equals(other.getData())) return false;
      }
      if (getSeat()
          != other.getSeat()) return false;
      if (java.lang.Float.floatToIntBits(getCoin())
          != java.lang.Float.floatToIntBits(
              other.getCoin())) return false;
      if (java.lang.Float.floatToIntBits(getRemain())
          != java.lang.Float.floatToIntBits(
              other.getRemain())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (37 * hash) + SEAT_FIELD_NUMBER;
      hash = (53 * hash) + getSeat();
      hash = (37 * hash) + COIN_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getCoin());
      hash = (37 * hash) + REMAIN_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getRemain());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.ShootAckOuterClass.ShootAck parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ShootAckOuterClass.ShootAck parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ShootAckOuterClass.ShootAck parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ShootAckOuterClass.ShootAck parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ShootAckOuterClass.ShootAck parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ShootAckOuterClass.ShootAck parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ShootAckOuterClass.ShootAck parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static protocol.ShootAckOuterClass.ShootAck parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static protocol.ShootAckOuterClass.ShootAck parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static protocol.ShootAckOuterClass.ShootAck parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.ShootAckOuterClass.ShootAck parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static protocol.ShootAckOuterClass.ShootAck parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.ShootAckOuterClass.ShootAck prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.ShootAck}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.ShootAck)
        protocol.ShootAckOuterClass.ShootAckOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.ShootAckOuterClass.internal_static_protocol_ShootAck_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.ShootAckOuterClass.internal_static_protocol_ShootAck_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.ShootAckOuterClass.ShootAck.class, protocol.ShootAckOuterClass.ShootAck.Builder.class);
      }

      // Construct using protocol.ShootAckOuterClass.ShootAck.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetDataFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        data_ = null;
        if (dataBuilder_ != null) {
          dataBuilder_.dispose();
          dataBuilder_ = null;
        }
        seat_ = 0;
        coin_ = 0F;
        remain_ = 0F;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.ShootAckOuterClass.internal_static_protocol_ShootAck_descriptor;
      }

      @java.lang.Override
      public protocol.ShootAckOuterClass.ShootAck getDefaultInstanceForType() {
        return protocol.ShootAckOuterClass.ShootAck.getDefaultInstance();
      }

      @java.lang.Override
      public protocol.ShootAckOuterClass.ShootAck build() {
        protocol.ShootAckOuterClass.ShootAck result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protocol.ShootAckOuterClass.ShootAck buildPartial() {
        protocol.ShootAckOuterClass.ShootAck result = new protocol.ShootAckOuterClass.ShootAck(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(protocol.ShootAckOuterClass.ShootAck result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.data_ = dataBuilder_ == null
              ? data_
              : dataBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.seat_ = seat_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.coin_ = coin_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.remain_ = remain_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.ShootAckOuterClass.ShootAck) {
          return mergeFrom((protocol.ShootAckOuterClass.ShootAck)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.ShootAckOuterClass.ShootAck other) {
        if (other == protocol.ShootAckOuterClass.ShootAck.getDefaultInstance()) return this;
        if (other.hasData()) {
          mergeData(other.getData());
        }
        if (other.getSeat() != 0) {
          setSeat(other.getSeat());
        }
        if (java.lang.Float.floatToRawIntBits(other.getCoin()) != 0) {
          setCoin(other.getCoin());
        }
        if (java.lang.Float.floatToRawIntBits(other.getRemain()) != 0) {
          setRemain(other.getRemain());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    internalGetDataFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                seat_ = input.readUInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 29: {
                coin_ = input.readFloat();
                bitField0_ |= 0x00000004;
                break;
              } // case 29
              case 37: {
                remain_ = input.readFloat();
                bitField0_ |= 0x00000008;
                break;
              } // case 37
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private protocol.LC.ShootReq data_;
      private com.google.protobuf.SingleFieldBuilder<
          protocol.LC.ShootReq, protocol.LC.ShootReq.Builder, protocol.LC.ShootReqOrBuilder> dataBuilder_;
      /**
       * <code>.protocol.ShootReq data = 1;</code>
       * @return Whether the data field is set.
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.protocol.ShootReq data = 1;</code>
       * @return The data.
       */
      public protocol.LC.ShootReq getData() {
        if (dataBuilder_ == null) {
          return data_ == null ? protocol.LC.ShootReq.getDefaultInstance() : data_;
        } else {
          return dataBuilder_.getMessage();
        }
      }
      /**
       * <code>.protocol.ShootReq data = 1;</code>
       */
      public Builder setData(protocol.LC.ShootReq value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
        } else {
          dataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.ShootReq data = 1;</code>
       */
      public Builder setData(
          protocol.LC.ShootReq.Builder builderForValue) {
        if (dataBuilder_ == null) {
          data_ = builderForValue.build();
        } else {
          dataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.ShootReq data = 1;</code>
       */
      public Builder mergeData(protocol.LC.ShootReq value) {
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            data_ != null &&
            data_ != protocol.LC.ShootReq.getDefaultInstance()) {
            getDataBuilder().mergeFrom(value);
          } else {
            data_ = value;
          }
        } else {
          dataBuilder_.mergeFrom(value);
        }
        if (data_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.protocol.ShootReq data = 1;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = null;
        if (dataBuilder_ != null) {
          dataBuilder_.dispose();
          dataBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.ShootReq data = 1;</code>
       */
      public protocol.LC.ShootReq.Builder getDataBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return internalGetDataFieldBuilder().getBuilder();
      }
      /**
       * <code>.protocol.ShootReq data = 1;</code>
       */
      public protocol.LC.ShootReqOrBuilder getDataOrBuilder() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilder();
        } else {
          return data_ == null ?
              protocol.LC.ShootReq.getDefaultInstance() : data_;
        }
      }
      /**
       * <code>.protocol.ShootReq data = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          protocol.LC.ShootReq, protocol.LC.ShootReq.Builder, protocol.LC.ShootReqOrBuilder> 
          internalGetDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              protocol.LC.ShootReq, protocol.LC.ShootReq.Builder, protocol.LC.ShootReqOrBuilder>(
                  getData(),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }

      private int seat_ ;
      /**
       * <code>uint32 seat = 2;</code>
       * @return The seat.
       */
      @java.lang.Override
      public int getSeat() {
        return seat_;
      }
      /**
       * <code>uint32 seat = 2;</code>
       * @param value The seat to set.
       * @return This builder for chaining.
       */
      public Builder setSeat(int value) {

        seat_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 seat = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSeat() {
        bitField0_ = (bitField0_ & ~0x00000002);
        seat_ = 0;
        onChanged();
        return this;
      }

      private float coin_ ;
      /**
       * <code>float coin = 3;</code>
       * @return The coin.
       */
      @java.lang.Override
      public float getCoin() {
        return coin_;
      }
      /**
       * <code>float coin = 3;</code>
       * @param value The coin to set.
       * @return This builder for chaining.
       */
      public Builder setCoin(float value) {

        coin_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>float coin = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCoin() {
        bitField0_ = (bitField0_ & ~0x00000004);
        coin_ = 0F;
        onChanged();
        return this;
      }

      private float remain_ ;
      /**
       * <code>float remain = 4;</code>
       * @return The remain.
       */
      @java.lang.Override
      public float getRemain() {
        return remain_;
      }
      /**
       * <code>float remain = 4;</code>
       * @param value The remain to set.
       * @return This builder for chaining.
       */
      public Builder setRemain(float value) {

        remain_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>float remain = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearRemain() {
        bitField0_ = (bitField0_ & ~0x00000008);
        remain_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protocol.ShootAck)
    }

    // @@protoc_insertion_point(class_scope:protocol.ShootAck)
    private static final protocol.ShootAckOuterClass.ShootAck DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.ShootAckOuterClass.ShootAck();
    }

    public static protocol.ShootAckOuterClass.ShootAck getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ShootAck>
        PARSER = new com.google.protobuf.AbstractParser<ShootAck>() {
      @java.lang.Override
      public ShootAck parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ShootAck> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ShootAck> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protocol.ShootAckOuterClass.ShootAck getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_ShootAck_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_ShootAck_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016ShootAck.proto\022\010protocol\032\010LC.proto\"X\n\010" +
      "ShootAck\022 \n\004data\030\001 \001(\0132\022.protocol.ShootR" +
      "eq\022\014\n\004seat\030\002 \001(\r\022\014\n\004coin\030\003 \001(\002\022\016\n\006remain" +
      "\030\004 \001(\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protocol.LC.getDescriptor(),
        });
    internal_static_protocol_ShootAck_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_ShootAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_ShootAck_descriptor,
        new java.lang.String[] { "Data", "Seat", "Coin", "Remain", });
    descriptor.resolveAllFeaturesImmutable();
    protocol.LC.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
