// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ShootReq2.proto
// Protobuf Java Version: 4.30.0

package protocol;

public final class ShootReq2OuterClass {
  private ShootReq2OuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 0,
      /* suffix= */ "",
      ShootReq2OuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code protocol.BulletType2}
   */
  public enum BulletType2
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Normal = 0;</code>
     */
    Normal(0),
    /**
     * <code>Lock = 1;</code>
     */
    Lock(1),
    /**
     * <code>Dragon = 2;</code>
     */
    Dragon(2),
    /**
     * <code>DragonOther = 3;</code>
     */
    DragonOther(3),
    /**
     * <code>Phoenix = 4;</code>
     */
    Phoenix(4),
    /**
     * <code>Drill = 5;</code>
     */
    Drill(5),
    /**
     * <code>Laser = 6;</code>
     */
    Laser(6),
    /**
     * <code>Fire = 7;</code>
     */
    Fire(7),
    /**
     * <code>Free = 20;</code>
     */
    Free(20),
    /**
     * <code>FreeDrill = 21;</code>
     */
    FreeDrill(21),
    /**
     * <code>FreeNet = 22;</code>
     */
    FreeNet(22),
    /**
     * <code>Energy = 23;</code>
     */
    Energy(23),
    /**
     * <code>FreeSpin = 24;</code>
     */
    FreeSpin(24),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 0,
        /* suffix= */ "",
        BulletType2.class.getName());
    }
    /**
     * <code>Normal = 0;</code>
     */
    public static final int Normal_VALUE = 0;
    /**
     * <code>Lock = 1;</code>
     */
    public static final int Lock_VALUE = 1;
    /**
     * <code>Dragon = 2;</code>
     */
    public static final int Dragon_VALUE = 2;
    /**
     * <code>DragonOther = 3;</code>
     */
    public static final int DragonOther_VALUE = 3;
    /**
     * <code>Phoenix = 4;</code>
     */
    public static final int Phoenix_VALUE = 4;
    /**
     * <code>Drill = 5;</code>
     */
    public static final int Drill_VALUE = 5;
    /**
     * <code>Laser = 6;</code>
     */
    public static final int Laser_VALUE = 6;
    /**
     * <code>Fire = 7;</code>
     */
    public static final int Fire_VALUE = 7;
    /**
     * <code>Free = 20;</code>
     */
    public static final int Free_VALUE = 20;
    /**
     * <code>FreeDrill = 21;</code>
     */
    public static final int FreeDrill_VALUE = 21;
    /**
     * <code>FreeNet = 22;</code>
     */
    public static final int FreeNet_VALUE = 22;
    /**
     * <code>Energy = 23;</code>
     */
    public static final int Energy_VALUE = 23;
    /**
     * <code>FreeSpin = 24;</code>
     */
    public static final int FreeSpin_VALUE = 24;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BulletType2 valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static BulletType2 forNumber(int value) {
      switch (value) {
        case 0: return Normal;
        case 1: return Lock;
        case 2: return Dragon;
        case 3: return DragonOther;
        case 4: return Phoenix;
        case 5: return Drill;
        case 6: return Laser;
        case 7: return Fire;
        case 20: return Free;
        case 21: return FreeDrill;
        case 22: return FreeNet;
        case 23: return Energy;
        case 24: return FreeSpin;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BulletType2>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        BulletType2> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BulletType2>() {
            public BulletType2 findValueByNumber(int number) {
              return BulletType2.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protocol.ShootReq2OuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final BulletType2[] VALUES = values();

    public static BulletType2 valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private BulletType2(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protocol.BulletType2)
  }

  public interface Point2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.Point2)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double x = 1;</code>
     * @return The x.
     */
    double getX();

    /**
     * <code>double y = 2;</code>
     * @return The y.
     */
    double getY();
  }
  /**
   * Protobuf type {@code protocol.Point2}
   */
  public static final class Point2 extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protocol.Point2)
      Point2OrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 0,
        /* suffix= */ "",
        Point2.class.getName());
    }
    // Use Point2.newBuilder() to construct.
    private Point2(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Point2() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.ShootReq2OuterClass.internal_static_protocol_Point2_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.ShootReq2OuterClass.internal_static_protocol_Point2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.ShootReq2OuterClass.Point2.class, protocol.ShootReq2OuterClass.Point2.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private double x_ = 0D;
    /**
     * <code>double x = 1;</code>
     * @return The x.
     */
    @java.lang.Override
    public double getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private double y_ = 0D;
    /**
     * <code>double y = 2;</code>
     * @return The y.
     */
    @java.lang.Override
    public double getY() {
      return y_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Double.doubleToRawLongBits(x_) != 0) {
        output.writeDouble(1, x_);
      }
      if (java.lang.Double.doubleToRawLongBits(y_) != 0) {
        output.writeDouble(2, y_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Double.doubleToRawLongBits(x_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, x_);
      }
      if (java.lang.Double.doubleToRawLongBits(y_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, y_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.ShootReq2OuterClass.Point2)) {
        return super.equals(obj);
      }
      protocol.ShootReq2OuterClass.Point2 other = (protocol.ShootReq2OuterClass.Point2) obj;

      if (java.lang.Double.doubleToLongBits(getX())
          != java.lang.Double.doubleToLongBits(
              other.getX())) return false;
      if (java.lang.Double.doubleToLongBits(getY())
          != java.lang.Double.doubleToLongBits(
              other.getY())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getX()));
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getY()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.ShootReq2OuterClass.Point2 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ShootReq2OuterClass.Point2 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ShootReq2OuterClass.Point2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ShootReq2OuterClass.Point2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ShootReq2OuterClass.Point2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ShootReq2OuterClass.Point2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ShootReq2OuterClass.Point2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static protocol.ShootReq2OuterClass.Point2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static protocol.ShootReq2OuterClass.Point2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static protocol.ShootReq2OuterClass.Point2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.ShootReq2OuterClass.Point2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static protocol.ShootReq2OuterClass.Point2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.ShootReq2OuterClass.Point2 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.Point2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.Point2)
        protocol.ShootReq2OuterClass.Point2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.ShootReq2OuterClass.internal_static_protocol_Point2_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.ShootReq2OuterClass.internal_static_protocol_Point2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.ShootReq2OuterClass.Point2.class, protocol.ShootReq2OuterClass.Point2.Builder.class);
      }

      // Construct using protocol.ShootReq2OuterClass.Point2.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        x_ = 0D;
        y_ = 0D;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.ShootReq2OuterClass.internal_static_protocol_Point2_descriptor;
      }

      @java.lang.Override
      public protocol.ShootReq2OuterClass.Point2 getDefaultInstanceForType() {
        return protocol.ShootReq2OuterClass.Point2.getDefaultInstance();
      }

      @java.lang.Override
      public protocol.ShootReq2OuterClass.Point2 build() {
        protocol.ShootReq2OuterClass.Point2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protocol.ShootReq2OuterClass.Point2 buildPartial() {
        protocol.ShootReq2OuterClass.Point2 result = new protocol.ShootReq2OuterClass.Point2(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(protocol.ShootReq2OuterClass.Point2 result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.x_ = x_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.y_ = y_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.ShootReq2OuterClass.Point2) {
          return mergeFrom((protocol.ShootReq2OuterClass.Point2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.ShootReq2OuterClass.Point2 other) {
        if (other == protocol.ShootReq2OuterClass.Point2.getDefaultInstance()) return this;
        if (java.lang.Double.doubleToRawLongBits(other.getX()) != 0) {
          setX(other.getX());
        }
        if (java.lang.Double.doubleToRawLongBits(other.getY()) != 0) {
          setY(other.getY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {
                x_ = input.readDouble();
                bitField0_ |= 0x00000001;
                break;
              } // case 9
              case 17: {
                y_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private double x_ ;
      /**
       * <code>double x = 1;</code>
       * @return The x.
       */
      @java.lang.Override
      public double getX() {
        return x_;
      }
      /**
       * <code>double x = 1;</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(double value) {

        x_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>double x = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0D;
        onChanged();
        return this;
      }

      private double y_ ;
      /**
       * <code>double y = 2;</code>
       * @return The y.
       */
      @java.lang.Override
      public double getY() {
        return y_;
      }
      /**
       * <code>double y = 2;</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(double value) {

        y_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>double y = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protocol.Point2)
    }

    // @@protoc_insertion_point(class_scope:protocol.Point2)
    private static final protocol.ShootReq2OuterClass.Point2 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.ShootReq2OuterClass.Point2();
    }

    public static protocol.ShootReq2OuterClass.Point2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Point2>
        PARSER = new com.google.protobuf.AbstractParser<Point2>() {
      @java.lang.Override
      public Point2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Point2> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Point2> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protocol.ShootReq2OuterClass.Point2 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ShootReq2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.ShootReq2)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 bet = 1;</code>
     * @return The bet.
     */
    int getBet();

    /**
     * <code>.protocol.Point2 point = 2;</code>
     * @return Whether the point field is set.
     */
    boolean hasPoint();
    /**
     * <code>.protocol.Point2 point = 2;</code>
     * @return The point.
     */
    protocol.ShootReq2OuterClass.Point2 getPoint();
    /**
     * <code>.protocol.Point2 point = 2;</code>
     */
    protocol.ShootReq2OuterClass.Point2OrBuilder getPointOrBuilder();

    /**
     * <code>.protocol.BulletType2 type = 3;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.protocol.BulletType2 type = 3;</code>
     * @return The type.
     */
    protocol.ShootReq2OuterClass.BulletType2 getType();

    /**
     * <code>uint32 fishId = 4;</code>
     * @return The fishId.
     */
    int getFishId();

    /**
     * <code>uint32 bulletId = 5;</code>
     * @return The bulletId.
     */
    int getBulletId();
  }
  /**
   * Protobuf type {@code protocol.ShootReq2}
   */
  public static final class ShootReq2 extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protocol.ShootReq2)
      ShootReq2OrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 0,
        /* suffix= */ "",
        ShootReq2.class.getName());
    }
    // Use ShootReq2.newBuilder() to construct.
    private ShootReq2(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ShootReq2() {
      type_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.ShootReq2OuterClass.internal_static_protocol_ShootReq2_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.ShootReq2OuterClass.internal_static_protocol_ShootReq2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.ShootReq2OuterClass.ShootReq2.class, protocol.ShootReq2OuterClass.ShootReq2.Builder.class);
    }

    private int bitField0_;
    public static final int BET_FIELD_NUMBER = 1;
    private int bet_ = 0;
    /**
     * <code>int32 bet = 1;</code>
     * @return The bet.
     */
    @java.lang.Override
    public int getBet() {
      return bet_;
    }

    public static final int POINT_FIELD_NUMBER = 2;
    private protocol.ShootReq2OuterClass.Point2 point_;
    /**
     * <code>.protocol.Point2 point = 2;</code>
     * @return Whether the point field is set.
     */
    @java.lang.Override
    public boolean hasPoint() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.protocol.Point2 point = 2;</code>
     * @return The point.
     */
    @java.lang.Override
    public protocol.ShootReq2OuterClass.Point2 getPoint() {
      return point_ == null ? protocol.ShootReq2OuterClass.Point2.getDefaultInstance() : point_;
    }
    /**
     * <code>.protocol.Point2 point = 2;</code>
     */
    @java.lang.Override
    public protocol.ShootReq2OuterClass.Point2OrBuilder getPointOrBuilder() {
      return point_ == null ? protocol.ShootReq2OuterClass.Point2.getDefaultInstance() : point_;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_ = 0;
    /**
     * <code>.protocol.BulletType2 type = 3;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.protocol.BulletType2 type = 3;</code>
     * @return The type.
     */
    @java.lang.Override public protocol.ShootReq2OuterClass.BulletType2 getType() {
      protocol.ShootReq2OuterClass.BulletType2 result = protocol.ShootReq2OuterClass.BulletType2.forNumber(type_);
      return result == null ? protocol.ShootReq2OuterClass.BulletType2.UNRECOGNIZED : result;
    }

    public static final int FISHID_FIELD_NUMBER = 4;
    private int fishId_ = 0;
    /**
     * <code>uint32 fishId = 4;</code>
     * @return The fishId.
     */
    @java.lang.Override
    public int getFishId() {
      return fishId_;
    }

    public static final int BULLETID_FIELD_NUMBER = 5;
    private int bulletId_ = 0;
    /**
     * <code>uint32 bulletId = 5;</code>
     * @return The bulletId.
     */
    @java.lang.Override
    public int getBulletId() {
      return bulletId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (bet_ != 0) {
        output.writeInt32(1, bet_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getPoint());
      }
      if (type_ != protocol.ShootReq2OuterClass.BulletType2.Normal.getNumber()) {
        output.writeEnum(3, type_);
      }
      if (fishId_ != 0) {
        output.writeUInt32(4, fishId_);
      }
      if (bulletId_ != 0) {
        output.writeUInt32(5, bulletId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (bet_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, bet_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPoint());
      }
      if (type_ != protocol.ShootReq2OuterClass.BulletType2.Normal.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_);
      }
      if (fishId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, fishId_);
      }
      if (bulletId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, bulletId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.ShootReq2OuterClass.ShootReq2)) {
        return super.equals(obj);
      }
      protocol.ShootReq2OuterClass.ShootReq2 other = (protocol.ShootReq2OuterClass.ShootReq2) obj;

      if (getBet()
          != other.getBet()) return false;
      if (hasPoint() != other.hasPoint()) return false;
      if (hasPoint()) {
        if (!getPoint()
            .equals(other.getPoint())) return false;
      }
      if (type_ != other.type_) return false;
      if (getFishId()
          != other.getFishId()) return false;
      if (getBulletId()
          != other.getBulletId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BET_FIELD_NUMBER;
      hash = (53 * hash) + getBet();
      if (hasPoint()) {
        hash = (37 * hash) + POINT_FIELD_NUMBER;
        hash = (53 * hash) + getPoint().hashCode();
      }
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + FISHID_FIELD_NUMBER;
      hash = (53 * hash) + getFishId();
      hash = (37 * hash) + BULLETID_FIELD_NUMBER;
      hash = (53 * hash) + getBulletId();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.ShootReq2OuterClass.ShootReq2 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ShootReq2OuterClass.ShootReq2 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ShootReq2OuterClass.ShootReq2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ShootReq2OuterClass.ShootReq2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ShootReq2OuterClass.ShootReq2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ShootReq2OuterClass.ShootReq2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ShootReq2OuterClass.ShootReq2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static protocol.ShootReq2OuterClass.ShootReq2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static protocol.ShootReq2OuterClass.ShootReq2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static protocol.ShootReq2OuterClass.ShootReq2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.ShootReq2OuterClass.ShootReq2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static protocol.ShootReq2OuterClass.ShootReq2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.ShootReq2OuterClass.ShootReq2 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.ShootReq2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.ShootReq2)
        protocol.ShootReq2OuterClass.ShootReq2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.ShootReq2OuterClass.internal_static_protocol_ShootReq2_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.ShootReq2OuterClass.internal_static_protocol_ShootReq2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.ShootReq2OuterClass.ShootReq2.class, protocol.ShootReq2OuterClass.ShootReq2.Builder.class);
      }

      // Construct using protocol.ShootReq2OuterClass.ShootReq2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetPointFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        bet_ = 0;
        point_ = null;
        if (pointBuilder_ != null) {
          pointBuilder_.dispose();
          pointBuilder_ = null;
        }
        type_ = 0;
        fishId_ = 0;
        bulletId_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.ShootReq2OuterClass.internal_static_protocol_ShootReq2_descriptor;
      }

      @java.lang.Override
      public protocol.ShootReq2OuterClass.ShootReq2 getDefaultInstanceForType() {
        return protocol.ShootReq2OuterClass.ShootReq2.getDefaultInstance();
      }

      @java.lang.Override
      public protocol.ShootReq2OuterClass.ShootReq2 build() {
        protocol.ShootReq2OuterClass.ShootReq2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protocol.ShootReq2OuterClass.ShootReq2 buildPartial() {
        protocol.ShootReq2OuterClass.ShootReq2 result = new protocol.ShootReq2OuterClass.ShootReq2(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(protocol.ShootReq2OuterClass.ShootReq2 result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.bet_ = bet_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.point_ = pointBuilder_ == null
              ? point_
              : pointBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.type_ = type_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.fishId_ = fishId_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.bulletId_ = bulletId_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.ShootReq2OuterClass.ShootReq2) {
          return mergeFrom((protocol.ShootReq2OuterClass.ShootReq2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.ShootReq2OuterClass.ShootReq2 other) {
        if (other == protocol.ShootReq2OuterClass.ShootReq2.getDefaultInstance()) return this;
        if (other.getBet() != 0) {
          setBet(other.getBet());
        }
        if (other.hasPoint()) {
          mergePoint(other.getPoint());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getFishId() != 0) {
          setFishId(other.getFishId());
        }
        if (other.getBulletId() != 0) {
          setBulletId(other.getBulletId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                bet_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    internalGetPointFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                type_ = input.readEnum();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                fishId_ = input.readUInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                bulletId_ = input.readUInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int bet_ ;
      /**
       * <code>int32 bet = 1;</code>
       * @return The bet.
       */
      @java.lang.Override
      public int getBet() {
        return bet_;
      }
      /**
       * <code>int32 bet = 1;</code>
       * @param value The bet to set.
       * @return This builder for chaining.
       */
      public Builder setBet(int value) {

        bet_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 bet = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBet() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bet_ = 0;
        onChanged();
        return this;
      }

      private protocol.ShootReq2OuterClass.Point2 point_;
      private com.google.protobuf.SingleFieldBuilder<
          protocol.ShootReq2OuterClass.Point2, protocol.ShootReq2OuterClass.Point2.Builder, protocol.ShootReq2OuterClass.Point2OrBuilder> pointBuilder_;
      /**
       * <code>.protocol.Point2 point = 2;</code>
       * @return Whether the point field is set.
       */
      public boolean hasPoint() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.protocol.Point2 point = 2;</code>
       * @return The point.
       */
      public protocol.ShootReq2OuterClass.Point2 getPoint() {
        if (pointBuilder_ == null) {
          return point_ == null ? protocol.ShootReq2OuterClass.Point2.getDefaultInstance() : point_;
        } else {
          return pointBuilder_.getMessage();
        }
      }
      /**
       * <code>.protocol.Point2 point = 2;</code>
       */
      public Builder setPoint(protocol.ShootReq2OuterClass.Point2 value) {
        if (pointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          point_ = value;
        } else {
          pointBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.Point2 point = 2;</code>
       */
      public Builder setPoint(
          protocol.ShootReq2OuterClass.Point2.Builder builderForValue) {
        if (pointBuilder_ == null) {
          point_ = builderForValue.build();
        } else {
          pointBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.Point2 point = 2;</code>
       */
      public Builder mergePoint(protocol.ShootReq2OuterClass.Point2 value) {
        if (pointBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            point_ != null &&
            point_ != protocol.ShootReq2OuterClass.Point2.getDefaultInstance()) {
            getPointBuilder().mergeFrom(value);
          } else {
            point_ = value;
          }
        } else {
          pointBuilder_.mergeFrom(value);
        }
        if (point_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.protocol.Point2 point = 2;</code>
       */
      public Builder clearPoint() {
        bitField0_ = (bitField0_ & ~0x00000002);
        point_ = null;
        if (pointBuilder_ != null) {
          pointBuilder_.dispose();
          pointBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.Point2 point = 2;</code>
       */
      public protocol.ShootReq2OuterClass.Point2.Builder getPointBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return internalGetPointFieldBuilder().getBuilder();
      }
      /**
       * <code>.protocol.Point2 point = 2;</code>
       */
      public protocol.ShootReq2OuterClass.Point2OrBuilder getPointOrBuilder() {
        if (pointBuilder_ != null) {
          return pointBuilder_.getMessageOrBuilder();
        } else {
          return point_ == null ?
              protocol.ShootReq2OuterClass.Point2.getDefaultInstance() : point_;
        }
      }
      /**
       * <code>.protocol.Point2 point = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          protocol.ShootReq2OuterClass.Point2, protocol.ShootReq2OuterClass.Point2.Builder, protocol.ShootReq2OuterClass.Point2OrBuilder> 
          internalGetPointFieldBuilder() {
        if (pointBuilder_ == null) {
          pointBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              protocol.ShootReq2OuterClass.Point2, protocol.ShootReq2OuterClass.Point2.Builder, protocol.ShootReq2OuterClass.Point2OrBuilder>(
                  getPoint(),
                  getParentForChildren(),
                  isClean());
          point_ = null;
        }
        return pointBuilder_;
      }

      private int type_ = 0;
      /**
       * <code>.protocol.BulletType2 type = 3;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.protocol.BulletType2 type = 3;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.BulletType2 type = 3;</code>
       * @return The type.
       */
      @java.lang.Override
      public protocol.ShootReq2OuterClass.BulletType2 getType() {
        protocol.ShootReq2OuterClass.BulletType2 result = protocol.ShootReq2OuterClass.BulletType2.forNumber(type_);
        return result == null ? protocol.ShootReq2OuterClass.BulletType2.UNRECOGNIZED : result;
      }
      /**
       * <code>.protocol.BulletType2 type = 3;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(protocol.ShootReq2OuterClass.BulletType2 value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.BulletType2 type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 0;
        onChanged();
        return this;
      }

      private int fishId_ ;
      /**
       * <code>uint32 fishId = 4;</code>
       * @return The fishId.
       */
      @java.lang.Override
      public int getFishId() {
        return fishId_;
      }
      /**
       * <code>uint32 fishId = 4;</code>
       * @param value The fishId to set.
       * @return This builder for chaining.
       */
      public Builder setFishId(int value) {

        fishId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 fishId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFishId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        fishId_ = 0;
        onChanged();
        return this;
      }

      private int bulletId_ ;
      /**
       * <code>uint32 bulletId = 5;</code>
       * @return The bulletId.
       */
      @java.lang.Override
      public int getBulletId() {
        return bulletId_;
      }
      /**
       * <code>uint32 bulletId = 5;</code>
       * @param value The bulletId to set.
       * @return This builder for chaining.
       */
      public Builder setBulletId(int value) {

        bulletId_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 bulletId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearBulletId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        bulletId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protocol.ShootReq2)
    }

    // @@protoc_insertion_point(class_scope:protocol.ShootReq2)
    private static final protocol.ShootReq2OuterClass.ShootReq2 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.ShootReq2OuterClass.ShootReq2();
    }

    public static protocol.ShootReq2OuterClass.ShootReq2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ShootReq2>
        PARSER = new com.google.protobuf.AbstractParser<ShootReq2>() {
      @java.lang.Override
      public ShootReq2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ShootReq2> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ShootReq2> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protocol.ShootReq2OuterClass.ShootReq2 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_Point2_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_Point2_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_ShootReq2_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_ShootReq2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ShootReq2.proto\022\010protocol\"\036\n\006Point2\022\t\n" +
      "\001x\030\001 \001(\001\022\t\n\001y\030\002 \001(\001\"\200\001\n\tShootReq2\022\013\n\003bet" +
      "\030\001 \001(\005\022\037\n\005point\030\002 \001(\0132\020.protocol.Point2\022" +
      "#\n\004type\030\003 \001(\0162\025.protocol.BulletType2\022\016\n\006" +
      "fishId\030\004 \001(\r\022\020\n\010bulletId\030\005 \001(\r*\255\001\n\013Bulle" +
      "tType2\022\n\n\006Normal\020\000\022\010\n\004Lock\020\001\022\n\n\006Dragon\020\002" +
      "\022\017\n\013DragonOther\020\003\022\013\n\007Phoenix\020\004\022\t\n\005Drill\020" +
      "\005\022\t\n\005Laser\020\006\022\010\n\004Fire\020\007\022\010\n\004Free\020\024\022\r\n\tFree" +
      "Drill\020\025\022\013\n\007FreeNet\020\026\022\n\n\006Energy\020\027\022\014\n\010Free" +
      "Spin\020\030b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protocol_Point2_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_Point2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_Point2_descriptor,
        new java.lang.String[] { "X", "Y", });
    internal_static_protocol_ShootReq2_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_ShootReq2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_ShootReq2_descriptor,
        new java.lang.String[] { "Bet", "Point", "Type", "FishId", "BulletId", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
