// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: login_log.proto
// Protobuf Java Version: 4.30.0

package com.example.annin.protocol;

public final class LoginDataProto {
  private LoginDataProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 0,
      /* suffix= */ "",
      LoginDataProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BrowserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:annin_protocol.Browser)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * You must define this based on what `_r` represents
     * For now, a placeholder
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     * You must define this based on what `_r` represents
     * For now, a placeholder
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string version = 2;</code>
     * @return The version.
     */
    java.lang.String getVersion();
    /**
     * <code>string version = 2;</code>
     * @return The bytes for version.
     */
    com.google.protobuf.ByteString
        getVersionBytes();
  }
  /**
   * <pre>
   * Define the browser message if it's not already defined
   * </pre>
   *
   * Protobuf type {@code annin_protocol.Browser}
   */
  public static final class Browser extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:annin_protocol.Browser)
      BrowserOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 0,
        /* suffix= */ "",
        Browser.class.getName());
    }
    // Use Browser.newBuilder() to construct.
    private Browser(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Browser() {
      name_ = "";
      version_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.annin.protocol.LoginDataProto.internal_static_annin_protocol_Browser_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.annin.protocol.LoginDataProto.internal_static_annin_protocol_Browser_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.annin.protocol.LoginDataProto.Browser.class, com.example.annin.protocol.LoginDataProto.Browser.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <pre>
     * You must define this based on what `_r` represents
     * For now, a placeholder
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * You must define this based on what `_r` represents
     * For now, a placeholder
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object version_ = "";
    /**
     * <code>string version = 2;</code>
     * @return The version.
     */
    @java.lang.Override
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <code>string version = 2;</code>
     * @return The bytes for version.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(version_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, version_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(version_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, version_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.annin.protocol.LoginDataProto.Browser)) {
        return super.equals(obj);
      }
      com.example.annin.protocol.LoginDataProto.Browser other = (com.example.annin.protocol.LoginDataProto.Browser) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getVersion()
          .equals(other.getVersion())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.annin.protocol.LoginDataProto.Browser parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.annin.protocol.LoginDataProto.Browser parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.annin.protocol.LoginDataProto.Browser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.annin.protocol.LoginDataProto.Browser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.annin.protocol.LoginDataProto.Browser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.annin.protocol.LoginDataProto.Browser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.annin.protocol.LoginDataProto.Browser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.annin.protocol.LoginDataProto.Browser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.annin.protocol.LoginDataProto.Browser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.annin.protocol.LoginDataProto.Browser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.annin.protocol.LoginDataProto.Browser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.annin.protocol.LoginDataProto.Browser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.annin.protocol.LoginDataProto.Browser prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Define the browser message if it's not already defined
     * </pre>
     *
     * Protobuf type {@code annin_protocol.Browser}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:annin_protocol.Browser)
        com.example.annin.protocol.LoginDataProto.BrowserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.annin.protocol.LoginDataProto.internal_static_annin_protocol_Browser_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.annin.protocol.LoginDataProto.internal_static_annin_protocol_Browser_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.annin.protocol.LoginDataProto.Browser.class, com.example.annin.protocol.LoginDataProto.Browser.Builder.class);
      }

      // Construct using com.example.annin.protocol.LoginDataProto.Browser.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        name_ = "";
        version_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.annin.protocol.LoginDataProto.internal_static_annin_protocol_Browser_descriptor;
      }

      @java.lang.Override
      public com.example.annin.protocol.LoginDataProto.Browser getDefaultInstanceForType() {
        return com.example.annin.protocol.LoginDataProto.Browser.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.annin.protocol.LoginDataProto.Browser build() {
        com.example.annin.protocol.LoginDataProto.Browser result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.annin.protocol.LoginDataProto.Browser buildPartial() {
        com.example.annin.protocol.LoginDataProto.Browser result = new com.example.annin.protocol.LoginDataProto.Browser(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.annin.protocol.LoginDataProto.Browser result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.version_ = version_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.annin.protocol.LoginDataProto.Browser) {
          return mergeFrom((com.example.annin.protocol.LoginDataProto.Browser)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.annin.protocol.LoginDataProto.Browser other) {
        if (other == com.example.annin.protocol.LoginDataProto.Browser.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                version_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * You must define this based on what `_r` represents
       * For now, a placeholder
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * You must define this based on what `_r` represents
       * For now, a placeholder
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * You must define this based on what `_r` represents
       * For now, a placeholder
       * </pre>
       *
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * You must define this based on what `_r` represents
       * For now, a placeholder
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * You must define this based on what `_r` represents
       * For now, a placeholder
       * </pre>
       *
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object version_ = "";
      /**
       * <code>string version = 2;</code>
       * @return The version.
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string version = 2;</code>
       * @return The bytes for version.
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string version = 2;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        version_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string version = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        version_ = getDefaultInstance().getVersion();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string version = 2;</code>
       * @param value The bytes for version to set.
       * @return This builder for chaining.
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        version_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:annin_protocol.Browser)
    }

    // @@protoc_insertion_point(class_scope:annin_protocol.Browser)
    private static final com.example.annin.protocol.LoginDataProto.Browser DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.annin.protocol.LoginDataProto.Browser();
    }

    public static com.example.annin.protocol.LoginDataProto.Browser getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Browser>
        PARSER = new com.google.protobuf.AbstractParser<Browser>() {
      @java.lang.Override
      public Browser parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Browser> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Browser> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.annin.protocol.LoginDataProto.Browser getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoginLogDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:annin_protocol.LoginLogData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * T: 9 = string
     * </pre>
     *
     * <code>string os = 1;</code>
     * @return The os.
     */
    java.lang.String getOs();
    /**
     * <pre>
     * T: 9 = string
     * </pre>
     *
     * <code>string os = 1;</code>
     * @return The bytes for os.
     */
    com.google.protobuf.ByteString
        getOsBytes();

    /**
     * <pre>
     * T: 9 = string
     * </pre>
     *
     * <code>string language = 2;</code>
     * @return The language.
     */
    java.lang.String getLanguage();
    /**
     * <pre>
     * T: 9 = string
     * </pre>
     *
     * <code>string language = 2;</code>
     * @return The bytes for language.
     */
    com.google.protobuf.ByteString
        getLanguageBytes();

    /**
     * <pre>
     * T: message = Browser (was _r in JS)
     * </pre>
     *
     * <code>.annin_protocol.Browser browser = 3;</code>
     * @return Whether the browser field is set.
     */
    boolean hasBrowser();
    /**
     * <pre>
     * T: message = Browser (was _r in JS)
     * </pre>
     *
     * <code>.annin_protocol.Browser browser = 3;</code>
     * @return The browser.
     */
    com.example.annin.protocol.LoginDataProto.Browser getBrowser();
    /**
     * <pre>
     * T: message = Browser (was _r in JS)
     * </pre>
     *
     * <code>.annin_protocol.Browser browser = 3;</code>
     */
    com.example.annin.protocol.LoginDataProto.BrowserOrBuilder getBrowserOrBuilder();

    /**
     * <pre>
     * T: 9 = string
     * </pre>
     *
     * <code>string version = 4;</code>
     * @return The version.
     */
    java.lang.String getVersion();
    /**
     * <pre>
     * T: 9 = string
     * </pre>
     *
     * <code>string version = 4;</code>
     * @return The bytes for version.
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <pre>
     * T: 9 = string
     * </pre>
     *
     * <code>string model = 5;</code>
     * @return The model.
     */
    java.lang.String getModel();
    /**
     * <pre>
     * T: 9 = string
     * </pre>
     *
     * <code>string model = 5;</code>
     * @return The bytes for model.
     */
    com.google.protobuf.ByteString
        getModelBytes();
  }
  /**
   * Protobuf type {@code annin_protocol.LoginLogData}
   */
  public static final class LoginLogData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:annin_protocol.LoginLogData)
      LoginLogDataOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 0,
        /* suffix= */ "",
        LoginLogData.class.getName());
    }
    // Use LoginLogData.newBuilder() to construct.
    private LoginLogData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private LoginLogData() {
      os_ = "";
      language_ = "";
      version_ = "";
      model_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.annin.protocol.LoginDataProto.internal_static_annin_protocol_LoginLogData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.annin.protocol.LoginDataProto.internal_static_annin_protocol_LoginLogData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.annin.protocol.LoginDataProto.LoginLogData.class, com.example.annin.protocol.LoginDataProto.LoginLogData.Builder.class);
    }

    private int bitField0_;
    public static final int OS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object os_ = "";
    /**
     * <pre>
     * T: 9 = string
     * </pre>
     *
     * <code>string os = 1;</code>
     * @return The os.
     */
    @java.lang.Override
    public java.lang.String getOs() {
      java.lang.Object ref = os_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        os_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * T: 9 = string
     * </pre>
     *
     * <code>string os = 1;</code>
     * @return The bytes for os.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOsBytes() {
      java.lang.Object ref = os_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        os_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LANGUAGE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object language_ = "";
    /**
     * <pre>
     * T: 9 = string
     * </pre>
     *
     * <code>string language = 2;</code>
     * @return The language.
     */
    @java.lang.Override
    public java.lang.String getLanguage() {
      java.lang.Object ref = language_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        language_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * T: 9 = string
     * </pre>
     *
     * <code>string language = 2;</code>
     * @return The bytes for language.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLanguageBytes() {
      java.lang.Object ref = language_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        language_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BROWSER_FIELD_NUMBER = 3;
    private com.example.annin.protocol.LoginDataProto.Browser browser_;
    /**
     * <pre>
     * T: message = Browser (was _r in JS)
     * </pre>
     *
     * <code>.annin_protocol.Browser browser = 3;</code>
     * @return Whether the browser field is set.
     */
    @java.lang.Override
    public boolean hasBrowser() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * T: message = Browser (was _r in JS)
     * </pre>
     *
     * <code>.annin_protocol.Browser browser = 3;</code>
     * @return The browser.
     */
    @java.lang.Override
    public com.example.annin.protocol.LoginDataProto.Browser getBrowser() {
      return browser_ == null ? com.example.annin.protocol.LoginDataProto.Browser.getDefaultInstance() : browser_;
    }
    /**
     * <pre>
     * T: message = Browser (was _r in JS)
     * </pre>
     *
     * <code>.annin_protocol.Browser browser = 3;</code>
     */
    @java.lang.Override
    public com.example.annin.protocol.LoginDataProto.BrowserOrBuilder getBrowserOrBuilder() {
      return browser_ == null ? com.example.annin.protocol.LoginDataProto.Browser.getDefaultInstance() : browser_;
    }

    public static final int VERSION_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object version_ = "";
    /**
     * <pre>
     * T: 9 = string
     * </pre>
     *
     * <code>string version = 4;</code>
     * @return The version.
     */
    @java.lang.Override
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * T: 9 = string
     * </pre>
     *
     * <code>string version = 4;</code>
     * @return The bytes for version.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MODEL_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object model_ = "";
    /**
     * <pre>
     * T: 9 = string
     * </pre>
     *
     * <code>string model = 5;</code>
     * @return The model.
     */
    @java.lang.Override
    public java.lang.String getModel() {
      java.lang.Object ref = model_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        model_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * T: 9 = string
     * </pre>
     *
     * <code>string model = 5;</code>
     * @return The bytes for model.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getModelBytes() {
      java.lang.Object ref = model_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        model_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(os_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, os_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(language_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, language_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(3, getBrowser());
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(version_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, version_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(model_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, model_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(os_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, os_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(language_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, language_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getBrowser());
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(version_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, version_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(model_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, model_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.annin.protocol.LoginDataProto.LoginLogData)) {
        return super.equals(obj);
      }
      com.example.annin.protocol.LoginDataProto.LoginLogData other = (com.example.annin.protocol.LoginDataProto.LoginLogData) obj;

      if (!getOs()
          .equals(other.getOs())) return false;
      if (!getLanguage()
          .equals(other.getLanguage())) return false;
      if (hasBrowser() != other.hasBrowser()) return false;
      if (hasBrowser()) {
        if (!getBrowser()
            .equals(other.getBrowser())) return false;
      }
      if (!getVersion()
          .equals(other.getVersion())) return false;
      if (!getModel()
          .equals(other.getModel())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OS_FIELD_NUMBER;
      hash = (53 * hash) + getOs().hashCode();
      hash = (37 * hash) + LANGUAGE_FIELD_NUMBER;
      hash = (53 * hash) + getLanguage().hashCode();
      if (hasBrowser()) {
        hash = (37 * hash) + BROWSER_FIELD_NUMBER;
        hash = (53 * hash) + getBrowser().hashCode();
      }
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (37 * hash) + MODEL_FIELD_NUMBER;
      hash = (53 * hash) + getModel().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.annin.protocol.LoginDataProto.LoginLogData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.annin.protocol.LoginDataProto.LoginLogData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.annin.protocol.LoginDataProto.LoginLogData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.annin.protocol.LoginDataProto.LoginLogData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.annin.protocol.LoginDataProto.LoginLogData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.annin.protocol.LoginDataProto.LoginLogData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.annin.protocol.LoginDataProto.LoginLogData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.annin.protocol.LoginDataProto.LoginLogData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.annin.protocol.LoginDataProto.LoginLogData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.annin.protocol.LoginDataProto.LoginLogData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.annin.protocol.LoginDataProto.LoginLogData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.annin.protocol.LoginDataProto.LoginLogData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.annin.protocol.LoginDataProto.LoginLogData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code annin_protocol.LoginLogData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:annin_protocol.LoginLogData)
        com.example.annin.protocol.LoginDataProto.LoginLogDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.annin.protocol.LoginDataProto.internal_static_annin_protocol_LoginLogData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.annin.protocol.LoginDataProto.internal_static_annin_protocol_LoginLogData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.annin.protocol.LoginDataProto.LoginLogData.class, com.example.annin.protocol.LoginDataProto.LoginLogData.Builder.class);
      }

      // Construct using com.example.annin.protocol.LoginDataProto.LoginLogData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetBrowserFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        os_ = "";
        language_ = "";
        browser_ = null;
        if (browserBuilder_ != null) {
          browserBuilder_.dispose();
          browserBuilder_ = null;
        }
        version_ = "";
        model_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.annin.protocol.LoginDataProto.internal_static_annin_protocol_LoginLogData_descriptor;
      }

      @java.lang.Override
      public com.example.annin.protocol.LoginDataProto.LoginLogData getDefaultInstanceForType() {
        return com.example.annin.protocol.LoginDataProto.LoginLogData.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.annin.protocol.LoginDataProto.LoginLogData build() {
        com.example.annin.protocol.LoginDataProto.LoginLogData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.annin.protocol.LoginDataProto.LoginLogData buildPartial() {
        com.example.annin.protocol.LoginDataProto.LoginLogData result = new com.example.annin.protocol.LoginDataProto.LoginLogData(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.annin.protocol.LoginDataProto.LoginLogData result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.os_ = os_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.language_ = language_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.browser_ = browserBuilder_ == null
              ? browser_
              : browserBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.version_ = version_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.model_ = model_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.annin.protocol.LoginDataProto.LoginLogData) {
          return mergeFrom((com.example.annin.protocol.LoginDataProto.LoginLogData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.annin.protocol.LoginDataProto.LoginLogData other) {
        if (other == com.example.annin.protocol.LoginDataProto.LoginLogData.getDefaultInstance()) return this;
        if (!other.getOs().isEmpty()) {
          os_ = other.os_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getLanguage().isEmpty()) {
          language_ = other.language_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasBrowser()) {
          mergeBrowser(other.getBrowser());
        }
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getModel().isEmpty()) {
          model_ = other.model_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                os_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                language_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    internalGetBrowserFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                version_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                model_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object os_ = "";
      /**
       * <pre>
       * T: 9 = string
       * </pre>
       *
       * <code>string os = 1;</code>
       * @return The os.
       */
      public java.lang.String getOs() {
        java.lang.Object ref = os_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          os_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * T: 9 = string
       * </pre>
       *
       * <code>string os = 1;</code>
       * @return The bytes for os.
       */
      public com.google.protobuf.ByteString
          getOsBytes() {
        java.lang.Object ref = os_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          os_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * T: 9 = string
       * </pre>
       *
       * <code>string os = 1;</code>
       * @param value The os to set.
       * @return This builder for chaining.
       */
      public Builder setOs(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        os_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * T: 9 = string
       * </pre>
       *
       * <code>string os = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOs() {
        os_ = getDefaultInstance().getOs();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * T: 9 = string
       * </pre>
       *
       * <code>string os = 1;</code>
       * @param value The bytes for os to set.
       * @return This builder for chaining.
       */
      public Builder setOsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        os_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object language_ = "";
      /**
       * <pre>
       * T: 9 = string
       * </pre>
       *
       * <code>string language = 2;</code>
       * @return The language.
       */
      public java.lang.String getLanguage() {
        java.lang.Object ref = language_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          language_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * T: 9 = string
       * </pre>
       *
       * <code>string language = 2;</code>
       * @return The bytes for language.
       */
      public com.google.protobuf.ByteString
          getLanguageBytes() {
        java.lang.Object ref = language_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          language_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * T: 9 = string
       * </pre>
       *
       * <code>string language = 2;</code>
       * @param value The language to set.
       * @return This builder for chaining.
       */
      public Builder setLanguage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        language_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * T: 9 = string
       * </pre>
       *
       * <code>string language = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLanguage() {
        language_ = getDefaultInstance().getLanguage();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * T: 9 = string
       * </pre>
       *
       * <code>string language = 2;</code>
       * @param value The bytes for language to set.
       * @return This builder for chaining.
       */
      public Builder setLanguageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        language_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private com.example.annin.protocol.LoginDataProto.Browser browser_;
      private com.google.protobuf.SingleFieldBuilder<
          com.example.annin.protocol.LoginDataProto.Browser, com.example.annin.protocol.LoginDataProto.Browser.Builder, com.example.annin.protocol.LoginDataProto.BrowserOrBuilder> browserBuilder_;
      /**
       * <pre>
       * T: message = Browser (was _r in JS)
       * </pre>
       *
       * <code>.annin_protocol.Browser browser = 3;</code>
       * @return Whether the browser field is set.
       */
      public boolean hasBrowser() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * T: message = Browser (was _r in JS)
       * </pre>
       *
       * <code>.annin_protocol.Browser browser = 3;</code>
       * @return The browser.
       */
      public com.example.annin.protocol.LoginDataProto.Browser getBrowser() {
        if (browserBuilder_ == null) {
          return browser_ == null ? com.example.annin.protocol.LoginDataProto.Browser.getDefaultInstance() : browser_;
        } else {
          return browserBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * T: message = Browser (was _r in JS)
       * </pre>
       *
       * <code>.annin_protocol.Browser browser = 3;</code>
       */
      public Builder setBrowser(com.example.annin.protocol.LoginDataProto.Browser value) {
        if (browserBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          browser_ = value;
        } else {
          browserBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * T: message = Browser (was _r in JS)
       * </pre>
       *
       * <code>.annin_protocol.Browser browser = 3;</code>
       */
      public Builder setBrowser(
          com.example.annin.protocol.LoginDataProto.Browser.Builder builderForValue) {
        if (browserBuilder_ == null) {
          browser_ = builderForValue.build();
        } else {
          browserBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * T: message = Browser (was _r in JS)
       * </pre>
       *
       * <code>.annin_protocol.Browser browser = 3;</code>
       */
      public Builder mergeBrowser(com.example.annin.protocol.LoginDataProto.Browser value) {
        if (browserBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            browser_ != null &&
            browser_ != com.example.annin.protocol.LoginDataProto.Browser.getDefaultInstance()) {
            getBrowserBuilder().mergeFrom(value);
          } else {
            browser_ = value;
          }
        } else {
          browserBuilder_.mergeFrom(value);
        }
        if (browser_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * T: message = Browser (was _r in JS)
       * </pre>
       *
       * <code>.annin_protocol.Browser browser = 3;</code>
       */
      public Builder clearBrowser() {
        bitField0_ = (bitField0_ & ~0x00000004);
        browser_ = null;
        if (browserBuilder_ != null) {
          browserBuilder_.dispose();
          browserBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * T: message = Browser (was _r in JS)
       * </pre>
       *
       * <code>.annin_protocol.Browser browser = 3;</code>
       */
      public com.example.annin.protocol.LoginDataProto.Browser.Builder getBrowserBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return internalGetBrowserFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * T: message = Browser (was _r in JS)
       * </pre>
       *
       * <code>.annin_protocol.Browser browser = 3;</code>
       */
      public com.example.annin.protocol.LoginDataProto.BrowserOrBuilder getBrowserOrBuilder() {
        if (browserBuilder_ != null) {
          return browserBuilder_.getMessageOrBuilder();
        } else {
          return browser_ == null ?
              com.example.annin.protocol.LoginDataProto.Browser.getDefaultInstance() : browser_;
        }
      }
      /**
       * <pre>
       * T: message = Browser (was _r in JS)
       * </pre>
       *
       * <code>.annin_protocol.Browser browser = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.example.annin.protocol.LoginDataProto.Browser, com.example.annin.protocol.LoginDataProto.Browser.Builder, com.example.annin.protocol.LoginDataProto.BrowserOrBuilder> 
          internalGetBrowserFieldBuilder() {
        if (browserBuilder_ == null) {
          browserBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.example.annin.protocol.LoginDataProto.Browser, com.example.annin.protocol.LoginDataProto.Browser.Builder, com.example.annin.protocol.LoginDataProto.BrowserOrBuilder>(
                  getBrowser(),
                  getParentForChildren(),
                  isClean());
          browser_ = null;
        }
        return browserBuilder_;
      }

      private java.lang.Object version_ = "";
      /**
       * <pre>
       * T: 9 = string
       * </pre>
       *
       * <code>string version = 4;</code>
       * @return The version.
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * T: 9 = string
       * </pre>
       *
       * <code>string version = 4;</code>
       * @return The bytes for version.
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * T: 9 = string
       * </pre>
       *
       * <code>string version = 4;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        version_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * T: 9 = string
       * </pre>
       *
       * <code>string version = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        version_ = getDefaultInstance().getVersion();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * T: 9 = string
       * </pre>
       *
       * <code>string version = 4;</code>
       * @param value The bytes for version to set.
       * @return This builder for chaining.
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        version_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object model_ = "";
      /**
       * <pre>
       * T: 9 = string
       * </pre>
       *
       * <code>string model = 5;</code>
       * @return The model.
       */
      public java.lang.String getModel() {
        java.lang.Object ref = model_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          model_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * T: 9 = string
       * </pre>
       *
       * <code>string model = 5;</code>
       * @return The bytes for model.
       */
      public com.google.protobuf.ByteString
          getModelBytes() {
        java.lang.Object ref = model_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          model_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * T: 9 = string
       * </pre>
       *
       * <code>string model = 5;</code>
       * @param value The model to set.
       * @return This builder for chaining.
       */
      public Builder setModel(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        model_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * T: 9 = string
       * </pre>
       *
       * <code>string model = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearModel() {
        model_ = getDefaultInstance().getModel();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * T: 9 = string
       * </pre>
       *
       * <code>string model = 5;</code>
       * @param value The bytes for model to set.
       * @return This builder for chaining.
       */
      public Builder setModelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        model_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:annin_protocol.LoginLogData)
    }

    // @@protoc_insertion_point(class_scope:annin_protocol.LoginLogData)
    private static final com.example.annin.protocol.LoginDataProto.LoginLogData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.annin.protocol.LoginDataProto.LoginLogData();
    }

    public static com.example.annin.protocol.LoginDataProto.LoginLogData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginLogData>
        PARSER = new com.google.protobuf.AbstractParser<LoginLogData>() {
      @java.lang.Override
      public LoginLogData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<LoginLogData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginLogData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.annin.protocol.LoginDataProto.LoginLogData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_annin_protocol_Browser_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_annin_protocol_Browser_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_annin_protocol_LoginLogData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_annin_protocol_LoginLogData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017login_log.proto\022\016annin_protocol\"(\n\007Bro" +
      "wser\022\014\n\004name\030\001 \001(\t\022\017\n\007version\030\002 \001(\t\"v\n\014L" +
      "oginLogData\022\n\n\002os\030\001 \001(\t\022\020\n\010language\030\002 \001(" +
      "\t\022(\n\007browser\030\003 \001(\0132\027.annin_protocol.Brow" +
      "ser\022\017\n\007version\030\004 \001(\t\022\r\n\005model\030\005 \001(\tB,\n\032c" +
      "om.example.annin.protocolB\016LoginDataProt" +
      "ob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_annin_protocol_Browser_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_annin_protocol_Browser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_annin_protocol_Browser_descriptor,
        new java.lang.String[] { "Name", "Version", });
    internal_static_annin_protocol_LoginLogData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_annin_protocol_LoginLogData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_annin_protocol_LoginLogData_descriptor,
        new java.lang.String[] { "Os", "Language", "Browser", "Version", "Model", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
